port:  5000
markdown: kramdown
name: "Chicago's Million Dollar Blocks"
url: http://mdb.datamade.us
encoding: utf-8
timezone: America/Chicago
description: "Every year, the State of Illinois spends an incredible amount of money on incarcerating people from Chicago's poorest neighborhoods."
gems:
  - jekyll-redirect-from